language: java
jdk:
  - openjdk8
  - openjdk11
cache:
  directories:
  - $HOME/.m2
notifications:
  irc:
    channels:
        - "chat.freenode.net#forge"
    on_success: change # default: always
    on_failure: always # default: always

